### ISSUE TITLE
Exponent Format

### ISSUE THREAD

**Issue by filippo-fonseca** [mathiumjs/mathiumjs#2]
Currently, the exponents on most functions have the following format:
`8^2`

Instead, what we want is this:
`8²`

**Comment by fangskillz** [comment]
`8<sup>2</sup>` => 8²

**Comment by fangskillz** [comment]
Update: Use this unicode to convert from 8^2 to 8². Example  `console.log('8\u00B2')`

**Comment by filippo-fonseca** [comment]
Fixed with TS support update
